# Build-time GLSL -> SPIR-V compilation for engine shaders.
#
# strata_add_shaders(<target>
#     SOURCE_DIR <dir>
#     SHADERS <relative path>...
#     [VARIANTS "<relative path>|<registered name>|<DEFINE>[,<DEFINE>...]" ...]
#     [INCLUDE_DIRS <dir>...])
#
# Every stage file (*.vert, *.frag, *.comp, *.geom, *.tesc, *.tese) is compiled by glslang into a
# header containing a uint32_t SPIR-V array. A generated registry source embeds them all into
# <target>; at runtime they are looked up by registered name through Strata::EmbeddedShaders
# (Strata/Renderer/EmbeddedShaders.h). The registered name is the path relative to SOURCE_DIR,
# or the explicit name given for a variant (same source compiled with extra defines).
#
# Shared code lives in *.glsl include files under SOURCE_DIR. Every shader depends on all of them,
# so editing an include recompiles all shaders (cheap, and immune to depfile parsing quirks).
# Only one target per build may embed shaders, since the registry defines the lookup functions.

function(strata_add_shaders target)
	cmake_parse_arguments(ARG "" "SOURCE_DIR" "SHADERS;VARIANTS;INCLUDE_DIRS" ${ARGN})
	if(NOT ARG_SOURCE_DIR)
		message(FATAL_ERROR "strata_add_shaders: SOURCE_DIR is required")
	endif()
	if(NOT TARGET glslang-standalone)
		message(FATAL_ERROR "strata_add_shaders: the glslang-standalone target is not available")
	endif()

	file(GLOB_RECURSE includeFiles CONFIGURE_DEPENDS "${ARG_SOURCE_DIR}/*.glsl")
	set(outputDir "${CMAKE_CURRENT_BINARY_DIR}/EmbeddedShaders")

	set(includeArgs "-I${ARG_SOURCE_DIR}")
	foreach(dir IN LISTS ARG_INCLUDE_DIRS)
		list(APPEND includeArgs "-I${dir}")
	endforeach()

	set(entries "")
	foreach(shader IN LISTS ARG_SHADERS)
		list(APPEND entries "${shader}|${shader}|")
	endforeach()
	list(APPEND entries ${ARG_VARIANTS})

	set(generatedHeaders "")
	set(registryIncludes "")
	set(registryEntries "")
	set(registeredNames "")
	foreach(entry IN LISTS entries)
		string(REPLACE "|" ";" parts "${entry}")
		list(LENGTH parts partCount)
		if(partCount LESS 2)
			message(FATAL_ERROR "strata_add_shaders: malformed shader entry '${entry}'")
		endif()
		list(GET parts 0 sourceRelative)
		list(GET parts 1 name)
		set(defineArgs "")
		if(partCount GREATER 2)
			list(GET parts 2 defines)
			if(defines)
				string(REPLACE "," ";" defineList "${defines}")
				foreach(define IN LISTS defineList)
					list(APPEND defineArgs "-D${define}")
				endforeach()
			endif()
		endif()

		if(name IN_LIST registeredNames)
			message(FATAL_ERROR "strata_add_shaders: duplicate shader name '${name}'")
		endif()
		list(APPEND registeredNames "${name}")

		set(source "${ARG_SOURCE_DIR}/${sourceRelative}")
		if(NOT EXISTS "${source}")
			message(FATAL_ERROR "strata_add_shaders: shader source '${source}' does not exist")
		endif()

		string(MAKE_C_IDENTIFIER "${name}" identifier)
		set(variableName "g_StrataShader_${identifier}")
		set(header "${outputDir}/${name}.h")
		get_filename_component(headerDir "${header}" DIRECTORY)
		file(MAKE_DIRECTORY "${headerDir}")

		add_custom_command(
			OUTPUT "${header}"
			COMMAND glslang-standalone -V --target-env vulkan1.2 --quiet
				${includeArgs} ${defineArgs} --vn ${variableName} -o "${header}" "${source}"
			DEPENDS "${source}" ${includeFiles} glslang-standalone
			COMMENT "Compiling shader ${name}"
			VERBATIM)

		list(APPEND generatedHeaders "${header}")
		string(APPEND registryIncludes "#include \"${name}.h\"\n")
		string(APPEND registryEntries "\t\t{ \"${name}\", ${variableName}, sizeof(${variableName}) },\n")
	endforeach()

	list(LENGTH registeredNames shaderCount)
	if(shaderCount EQUAL 0)
		message(FATAL_ERROR "strata_add_shaders: no shaders given")
	endif()

	set(registrySource "${outputDir}/EmbeddedShaderRegistry.cpp")
	file(CONFIGURE OUTPUT "${registrySource}" CONTENT
"// Generated by CMake/StrataShaders.cmake - do not edit.
#include <cstddef>
#include <cstdint>

${registryIncludes}
#include \"Strata/Renderer/EmbeddedShaders.h\"

namespace Strata::EmbeddedShaders
{
	static const EmbeddedShader s_Shaders[] = {
${registryEntries}	};

	std::span<const EmbeddedShader> GetAll()
	{
		return s_Shaders;
	}
}
")

	target_sources(${target} PRIVATE ${generatedHeaders} "${registrySource}")
	target_include_directories(${target} PRIVATE "${outputDir}")
	source_group("Generated Shaders" FILES ${generatedHeaders} "${registrySource}")
endfunction()
