# Writes the git commit a build is made from into a header, in script mode at build time (the StrataVersionCommit target in
# Strata/CMakeLists.txt):
#
#   cmake -DGIT_EXECUTABLE=<git or empty> -DSOURCE_DIR=<checkout> -DOUTPUT=<header> -P StrataVersionCommit.cmake
#
# The header defines ST_VERSION_COMMIT: the commit's short hash, or "unknown" without git or outside a checkout. It is only
# rewritten when that changes, so the files including it recompile only after a commit or a checkout.

set(commit "unknown")
if(GIT_EXECUTABLE)
	execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse --short=12 HEAD
		WORKING_DIRECTORY "${SOURCE_DIR}" RESULT_VARIABLE result OUTPUT_VARIABLE output OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
	if(result EQUAL 0 AND output MATCHES "^[0-9a-f]+$")
		set(commit "${output}")
	endif()
endif()

file(CONFIGURE OUTPUT "${OUTPUT}" CONTENT "#pragma once

// Generated by CMake/StrataVersionCommit.cmake at build time - do not edit.

// Short hash of the git commit the build was made from (\"unknown\" outside a git checkout).
#define ST_VERSION_COMMIT \"@commit@\"
" @ONLY)
