# Embeds binary files (fonts and other built-in data) into a target at configure time.
#
# strata_embed_file(<target> <file> <function>)
#
# Generates a source defining `std::span<const uint8_t> Strata::EmbeddedFiles::<function>()`, which returns the
# file's bytes; declare the function in a header of <target>. Editing the file re-runs the configure step.

function(strata_embed_file target file function)
	if(NOT EXISTS "${file}")
		message(FATAL_ERROR "strata_embed_file: '${file}' does not exist")
	endif()

	file(READ "${file}" contents HEX)
	string(LENGTH "${contents}" hexLength)
	if(hexLength EQUAL 0)
		message(FATAL_ERROR "strata_embed_file: '${file}' is empty")
	endif()
	# Two hex digits per byte, 32 bytes per line.
	string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${contents}")
	string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n\t\t\t" bytes "${bytes}")

	set(source "${CMAKE_CURRENT_BINARY_DIR}/Generated/Embedded/${function}.cpp")
	file(CONFIGURE OUTPUT "${source}" CONTENT
"// Generated by CMake/StrataEmbeddedFiles.cmake from ${file} - do not edit.
#include <cstdint>
#include <span>

namespace Strata::EmbeddedFiles
{
	namespace
	{
		const uint8_t c_Data[] = {
			${bytes}
		};
	}

	std::span<const uint8_t> ${function}()
	{
		return c_Data;
	}
}
")
	set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${file}")
	target_sources(${target} PRIVATE "${source}")
	source_group("Generated Files" FILES "${source}")
endfunction()
